### ISSUE TITLE
Webhook reposting.

### ISSUE THREAD

**Issue by Yeahhahaha** [MysteryPancake/Discord-Reposter#15]
Is there a way to just leave the webhook name alone and just make it a certain name? (/repostlive)

**Comment by MysteryPancake** [comment]
This can be done by removing [line 226](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L226).

If you want the bot to post the username but not rename itself, then also remove [lines 225 to 227](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L225-L227) and [line 229](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L229), keeping [line 228](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L228) which sends the name.

**Comment by Yeahhahaha** [comment]
> This can be done by removing [line 226](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L226).
> 
> If you want the bot to post the username but not rename itself, then also remove [lines 225 to 227](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L225-L227) and [line 229](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L229), keeping [line 228](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L228) which sends the name.
> 
> I will try to add a toggle for this once I get around to it

thank you for the quick reply, was also wondering if there is a way to make it send the message after a certain amount of seconds/mins/hours? - Using the /repostlivehook command.

**Comment by MysteryPancake** [comment]
This can be done with the [setTimeout](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=setTimeout) method of Discord.js. I think it will work if [line 487](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L487) is replaced with:
```
client.setTimeout(function() {
    repostLive(message);
}, 5000);
```
The delay time is in milliseconds, so 5000 is 5 seconds
