### ISSUE TITLE
Transfer Messages to another Server

### ISSUE THREAD

**Issue by MisterCookie1234** [MysteryPancake/Discord-Reposter#23]
Hello!

Unfortunatly im not very sure, how i get it to work that the bot copies messages from channel 1 on server 1 to channel 2 on server 2.

**Comment by MysteryPancake** [comment]
If the bot is on both servers, either of the following should work:

On channel 1 on server 1:
`/repost to <CHANNEL 2 ID>`

On channel 2 on server 2:
`/repost from <CHANNEL 1 ID>`

**Comment by MisterCookie1234** [comment]
Alright Thanks...
Since the Bot just.. stopped without reason, i would like to know if its possible to start on from a specific time or a specific message? I really really dont want to start all over again
