### ISSUE TITLE
Issues Setting Up Bot

### ISSUE THREAD

**Issue by bluekittyyoyo** [MysteryPancake/Discord-Reposter#30]
![log](https://user-images.githubusercontent.com/24984376/76296156-639db200-627b-11ea-824c-08b9ef7d4c87.png)
 I am completely new to creating bots and continually run into issues trying to set it up and run it. I'm unsure of what specifically to ask for as I am totally unfamiliar with this process. Any solutions are appreciated as soon as possible, this is a time sensitive issue that I would like to have dealt with by 3/11/20 11pm Mountain Standard Time. I realize this is specific and short notice, again any help is appreciated. 
[2020-03-10T08_20_06_985Z-debug.log](https://github.com/MysteryPancake/Discord-Reposter/files/4311318/2020-03-10T08_20_06_985Z-debug.log)

**Comment by MysteryPancake** [comment]
Where is the directory located? It seems that it cannot find the file "reposter.js" in "C:/Users/Kai". If it is in another directory, try using "cd" to set the current directory, then attempt to run "node reposter.js" again.
E.G. If the file was on the desktop in a folder called "Reposter":
```
cd "C:/Users/Kai/Desktop/Reposter"
node reposter.js
```

**Comment by MysteryPancake** [comment]
I'm sorry if this is past the deadline, but I am not very active on GitHub and I only just saw this issue.

**Comment by bluekittyyoyo** [comment]
Thank you for the response, and it is still before the deadline! I made sure the file could be accessed and that fixed the previous issue, however there is a new issue. "Error: Incorrect login details were provided."
![image](https://user-images.githubusercontent.com/24984376/76385623-c6e51e00-6327-11ea-803e-87caf99a4edb.png)
I very much appreciate the assistance.

**Comment by MysteryPancake** [comment]
The login line is causing an error for some reason:
```
client.login("<SECRET_BOT_TOKEN>").catch(console.error);
```

<SECRET_BOT_TOKEN> may not be replaced with a valid bot token. This does not include the <> symbols, so a token may look like this for example:
```
client.login("MTg-this-IzNzU3OTA5NjA-is.not-DCeFB-a.real-r4DQlO-t0ken-qerT0").catch(console.error);
```
A token can be obtained by logging into [Applications](https://discordapp.com/developers/applications), then clicking on your application -> Bot -> Token -> "Click to Reveal Token".

Bot setup tutorials cover these steps more in depth, as the setup process for any bot can be very confusing.

**Comment by bluekittyyoyo** [comment]
Put in a new token and that fixed it. The bot appears to be functioning fine! However I have one last question, how does one repost from a channel to one in another server? The bot is in both servers, I am just unsure of formatting the commands. Again, thank you so much!

**Comment by bluekittyyoyo** [comment]
Nevermind, I figured out how to get channel IDs and give it to the bot to repost from.
