### ISSUE TITLE
Loop messages between 2 channels

### ISSUE THREAD

**Issue by pNbaz** [MysteryPancake/Discord-Reposter#32]
Hello, if I link 2 channels to forward the messages back and forth, is there a way that the bot ignores his own messages? Right now if I link, as example:
channel A to send messages to channel B
channel B to send messages to channel A
The bot enters in a loop where it sees his own messages and this way it send a messages without end.

**Comment by MysteryPancake** [comment]
I think the bot could ignore itself by adding this below [line 221](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L221):
`if (message.author.user === client.user) return;`

**Comment by pNbaz** [comment]
Unfortunatelly, the issue is still there.
I've added the code, but the bot behaves the same, if both channels are added to list.

![image](https://user-images.githubusercontent.com/64265435/80309161-d20ee300-87db-11ea-887d-647a8297c302.png)

![image](https://user-images.githubusercontent.com/64265435/80309119-7fcdc200-87db-11ea-8d59-a822433937aa.png)

**Comment by MysteryPancake** [comment]
I am sorry, I think I made a mistake. I think it should have been this line instead:
`if (message.author.id === client.user.id) return;`
Please tell me if this works.

**Comment by pNbaz** [comment]
The bot works now as intended. Thanks alot for your time and help <3
