### ISSUE TITLE
Search and replace in embed

### ISSUE THREAD

**Issue by daveq86** [MysteryPancake/Discord-Reposter#36]
I love the search and replace function, but Would it be posible to add search an replace to “Embed’s” as well?

**Comment by MysteryPancake** [comment]
I tried to add this today, please tell me if it works or not!

**Comment by daveq86** [comment]
Thank you!! I will observe in the next few days and report back to you. Tx again.

**Comment by daveq86** [comment]
This works great! Thank you again for helping with this.
