### ISSUE TITLE
"Couldn't repost from...!"

### ISSUE THREAD

**Issue by arrrrik** [MysteryPancake/Discord-Reposter#4]
I got the bot to work once on my local machine and that's about it. Won't work on either my local or my AWS instance. Running the latest node.js (10.8.0) and discord.js (11.4), so there shouldn't any dependency issues. No errors kicked out in CMD logging. Just "Couldn't repost from #channel" or "Couldn't repost to #otherchannel".

/repost commands and /repost help both work correctly. Let me know if you need any other information.

**Comment by MysteryPancake** [comment]
Sorry, I forgot to mention, channel names should not have a tag, so instead of `/repost to #channel`, it should be `/repost to channel` (without the tag). I'll try to get it to work for tags as well, sorry

**Comment by MysteryPancake** [comment]
I only added the option to repost channels by name recently. Previously it had to be a channel id. I didn't even think that the obvious way to define a channel would be with the tag. Sorry, my fault!

**Comment by MysteryPancake** [comment]
Updated now, hopefully it will work with channel tags as well. Please tell me if this was the issue!

**Comment by arrrrik** [comment]
Yep, that's it. I didn't even think to remove the #! Thanks for the quick response!

**Comment by MysteryPancake** [comment]
That's fine, I hope it works for what you wanted. I was just checking GitHub at the same time I saw this
