### ISSUE TITLE
can u please help me with changing the bots status activity to `watching /repost help in 'n' servers with 'n' reposts? (or something similar)

### ISSUE THREAD

**Issue by Rayne231** [MysteryPancake/Discord-Reposter#40]

**Comment by MysteryPancake** [comment]
[Docs for setActivity are here](https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setActivity)
In this case the activity would probably be
```
client.user.setActivity(`/repost help in ${client.guilds.size} servers with ${Object.keys(config.active).length} reposts`, { type: "WATCHING" });
```
It might need to be changed on [line 12](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L12) and [line 38](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L38)

**Comment by Rayne231** [comment]
should i remove .catch(console.error)?

**Comment by Rayne231** [comment]
well thanks a lot i got it
