### ISSUE TITLE
Change Discord Rich Presence

### ISSUE THREAD

**Issue by Ectalite** [MysteryPancake/Discord-Reposter#8]
I would know if I there is way to change the discord rich presence ?

**Comment by MysteryPancake** [comment]
My bot sets the activity [on line 12](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L12) (if this is what you are referring to).

This is the text displayed below the bot's name, for example I set it as `"Watching X servers"`, and `Watching X reposts` [on line 42](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L42).

You can change the activity to whatever you want [using setActivity](https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setActivity).

**Comment by MysteryPancake** [comment]
If you mean an existing way to change the presence, there is currently no command for it. The bot activity is shared across all the servers it is on, so it may not be a good idea to add a command for this because anyone could change it on any server at any time.

**Comment by Ectalite** [comment]
I‘m hosting it on my raspberry at home and it‘s for friends servers. So i thing it‘s not a problem to add a command. But I thought to modify it in a config file.

**Comment by MysteryPancake** [comment]
I see what you mean, but for something like this I think it is better to [change from the code directly](https://github.com/MysteryPancake/Discord-Reposter/blob/master/reposter.js#L12). 

Discord.js makes it easy to [change the activity to custom values](https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=setActivity) which would be difficult to configure from a file.

For example, it would be very difficult to implement text such as `"Watching X reposts"` using a config file, as `X` is a variable which can only be accessed from the code.

Similarly, it would be difficult to implement text such as `"Watching X servers"`, as again X is a variable which would be difficult to refer to.

Although these are just two specific examples, it will only get messier the more people want to use.
